// Erweiterte Emoji-Suche mit deutschen Suchbegriffen
// Diese sollte außerhalb der Komponente definiert werden für bessere Performance
export const EMOJI_SEARCH_MAP: Record<string, string[]> = {
    // ===== SMILEYS & GESICHTER =====
    '😀': ['glücklich', 'lachen', 'freude', 'happy', 'smile', 'grin', 'fröhlich'],
    '😃': ['lachen', 'freude', 'glücklich', 'smile', 'happy', 'fröhlich'],
    '😄': ['lachen', 'freude', 'glücklich', 'smile', 'happy', 'augen', 'fröhlich'],
    '😁': ['grinsen', 'lachen', 'freude', 'smile', 'happy', 'zähne', 'fröhlich'],
    '😅': ['schweiß', 'lachen', 'nervös', 'peinlich', 'sweat', 'relief', 'erleichtert'],
    '😂': ['tränen', 'lachen', 'lustig', 'weinen', 'freude', 'lol', 'haha', 'witzig'],
    '🤣': ['rollen', 'lachen', 'lustig', 'tränen', 'rofl', 'witzig', 'komisch'],
    '😊': ['lächeln', 'freundlich', 'zufrieden', 'glücklich', 'nett', 'sweet'],
    '😇': ['engel', 'heilig', 'unschuldig', 'brav', 'angel', 'heiligenschein'],
    '🙂': ['lächeln', 'ok', 'neutral', 'freundlich', 'slight', 'smile'],
    '🙃': ['kopfüber', 'sarkastisch', 'ironisch', 'upside', 'down', 'verkehrt'],
    '😉': ['zwinkern', 'flirten', 'geheimnis', 'wink', 'augenzwinkern'],
    '😌': ['zufrieden', 'entspannt', 'relieved', 'erleichtert', 'ruhig'],
    '😍': ['verliebt', 'herzaugen', 'liebe', 'love', 'heart', 'eyes', 'schwärmen'],
    '🥰': ['verliebt', 'liebe', 'herzchen', 'süß', 'smiling', 'hearts', 'niedlich'],
    '😘': ['kuss', 'küsschen', 'kiss', 'liebe', 'love', 'herz'],
    '😗': ['kuss', 'küssen', 'kiss', 'liebe'],
    '😙': ['kuss', 'küssen', 'kiss', 'lächeln', 'smile'],
    '😚': ['kuss', 'küssen', 'kiss', 'augen', 'zu', 'closed', 'eyes'],
    '😋': ['lecker', 'zunge', 'essen', 'yum', 'tongue', 'tasty', 'schmecken'],
    '😛': ['zunge', 'frech', 'tongue', 'out', 'rausstrecken'],
    '😜': ['zunge', 'zwinkern', 'frech', 'tongue', 'wink', 'crazy'],
    '🤪': ['verrückt', 'crazy', 'wild', 'schief', 'zany', 'durchgeknallt'],
    '😝': ['zunge', 'geschlossen', 'augen', 'tongue', 'closed', 'eyes'],
    '🤑': ['geld', 'money', 'dollar', 'reich', 'gierig', 'greedy'],
    '🤗': ['umarmung', 'hug', 'umarmen', 'freundlich', 'herzlich'],
    '🤭': ['kichern', 'hand', 'mund', 'giggle', 'cover', 'mouth', 'lachen'],
    '🤫': ['leise', 'psst', 'shh', 'quiet', 'geheimnis', 'silence'],
    '🤔': ['denken', 'thinking', 'grübeln', 'nachdenken', 'überlegen'],
    '🤐': ['mund', 'verschlossen', 'schweigen', 'zipper', 'quiet', 'stumm'],
    '🤨': ['skeptisch', 'zweifel', 'raised', 'eyebrow', 'suspicious', 'misstrauisch'],
    '😐': ['neutral', 'expressionslos', 'blank', 'emotionslos'],
    '😑': ['expressionslos', 'genervt', 'blank', 'annoyed', 'neutral'],
    '😶': ['stumm', 'speechless', 'kein', 'mund', 'sprachlos'],
    '😏': ['selbstgefällig', 'smirk', 'frech', 'überheblich', 'smug'],
    '😒': ['gelangweilt', 'unamused', 'genervt', 'annoyed', 'meh'],
    '🙄': ['augen', 'rollen', 'genervt', 'eye', 'roll', 'annoyed'],
    '😬': ['grimace', 'peinlich', 'awkward', 'uncomfortable', 'zähne'],
    '🤥': ['lügen', 'pinocchio', 'lying', 'nase', 'unehrlich'],
    '😔': ['traurig', 'sad', 'depressed', 'down', 'niedergeschlagen'],
    '😪': ['müde', 'sleepy', 'tired', 'schlafen', 'exhausted'],
    '🤤': ['sabbern', 'drool', 'hunger', 'lecker', 'want'],
    '😴': ['schlafen', 'sleeping', 'tired', 'müde', 'sleep'],
    '😷': ['maske', 'krank', 'sick', 'mask', 'medical', 'covid'],
    '🤒': ['fieber', 'krank', 'sick', 'thermometer', 'ill'],
    '🤕': ['verletzt', 'bandage', 'hurt', 'injured', 'kopf'],
    '🤢': ['übel', 'krank', 'sick', 'nauseous', 'grün'],
    '🤮': ['kotzen', 'erbrechen', 'sick', 'vomit', 'ill'],
    '🤧': ['niesen', 'sneeze', 'krank', 'sick', 'cold'],
    '🥵': ['heiß', 'hot', 'schwitzen', 'sweat', 'warm'],
    '🥶': ['kalt', 'cold', 'frieren', 'freezing', 'blue'],
    '🥴': ['schwindelig', 'dizzy', 'drunk', 'woozy', 'confused'],
    '😵': ['schwindelig', 'dizzy', 'confused', 'knocked', 'out'],
    '🤯': ['mind', 'blown', 'exploding', 'head', 'unglaublich', 'wow'],
    '🤠': ['cowboy', 'hut', 'hat', 'western', 'texas'],
    '🥳': ['party', 'feier', 'celebration', 'geburtstag', 'birthday'],
    '😎': ['cool', 'sonnenbrille', 'sunglasses', 'awesome', 'swag'],
    '🤓': ['nerd', 'smart', 'glasses', 'brille', 'intelligent'],
    '🧐': ['monokel', 'fancy', 'distinguished', 'gentleman', 'classy'],

    // Negative Emotionen
    '😕': ['traurig', 'confused', 'sad', 'disappointed', 'enttäuscht'],
    '😟': ['worried', 'sorge', 'besorgt', 'ängstlich', 'concern'],
    '🙁': ['traurig', 'sad', 'frown', 'disappointed', 'down'],
    '☹️': ['traurig', 'sad', 'frown', 'upset', 'unglücklich'],
    '😮': ['überrascht', 'surprised', 'wow', 'open', 'mouth'],
    '😯': ['überrascht', 'surprised', 'hushed', 'wow', 'shocked'],
    '😲': ['schockiert', 'astonished', 'surprised', 'wow', 'unglaublich'],
    '😳': ['verlegen', 'flushed', 'embarrassed', 'peinlich', 'shy'],
    '🥺': ['pleading', 'betteln', 'puppy', 'eyes', 'süß', 'niedlich'],
    '😦': ['frowning', 'upset', 'sad', 'disappointed', 'besorgt'],
    '😧': ['anguished', 'worried', 'besorgt', 'upset', 'stressed'],
    '😨': ['fearful', 'afraid', 'scared', 'angst', 'frightened'],
    '😰': ['anxious', 'sweat', 'worried', 'nervous', 'ängstlich'],
    '😥': ['sad', 'disappointed', 'relieved', 'upset', 'traurig'],
    '😢': ['crying', 'weinen', 'sad', 'tears', 'tränen'],
    '😭': ['loudly', 'crying', 'weinen', 'sob', 'tränen', 'schluchzen'],
    '😱': ['scream', 'fear', 'shock', 'scared', 'angst', 'schreien'],
    '😖': ['confounded', 'frustrated', 'upset', 'confused', 'frustriert'],
    '😣': ['persevering', 'struggling', 'frustrated', 'anstrengend'],
    '😞': ['disappointed', 'sad', 'upset', 'enttäuscht', 'traurig'],
    '😓': ['downcast', 'sweat', 'sad', 'disappointed', 'schweiss'],
    '😩': ['weary', 'tired', 'frustrated', 'exhausted', 'müde'],
    '😫': ['tired', 'exhausted', 'weary', 'frustrated', 'erschöpft'],
    '🥱': ['yawning', 'tired', 'sleepy', 'bored', 'müde', 'gähnen'],
    '😤': ['huffing', 'angry', 'frustrated', 'mad', 'wütend'],
    '😡': ['pouting', 'angry', 'mad', 'furious', 'wütend', 'sauer'],
    '😠': ['angry', 'mad', 'upset', 'furious', 'wütend', 'böse'],
    '🤬': ['swearing', 'cursing', 'angry', 'mad', 'fluchen', 'schimpfen'],
    '😈': ['smiling', 'devil', 'evil', 'böse', 'teufel', 'purple'],
    '👿': ['angry', 'devil', 'evil', 'mad', 'böse', 'teufel'],
    '💀': ['skull', 'death', 'dead', 'totenkopf', 'tot', 'skelett'],
    '☠️': ['skull', 'crossbones', 'death', 'pirate', 'pirat', 'gift'],
    '💩': ['poop', 'shit', 'poo', 'kacke', 'scheisse', 'haufen'],
    '🤡': ['clown', 'joker', 'funny', 'lustig', 'zirkus'],
    '👹': ['ogre', 'monster', 'red', 'japanese', 'oni', 'rot'],
    '👺': ['goblin', 'japanese', 'tengu', 'red', 'long', 'nose'],
    '👻': ['ghost', 'geist', 'spook', 'halloween', 'scary'],
    '👽': ['alien', 'extraterrestrial', 'ufo', 'space', 'außerirdischer'],
    '👾': ['alien', 'monster', 'game', 'arcade', 'pixel', 'space'],
    '🤖': ['robot', 'bot', 'ai', 'machine', 'artificial'],

    // ===== GESTEN & KÖRPERTEILE =====
    '👋': ['winken', 'wave', 'hello', 'hallo', 'tschüss', 'bye'],
    '🤚': ['hand', 'raised', 'stop', 'high', 'five', 'stopp'],
    '🖐️': ['hand', 'fingers', 'five', 'palm', 'handfläche'],
    '✋': ['hand', 'stop', 'halt', 'raised', 'palm', 'stopp'],
    '🖖': ['vulcan', 'spock', 'star', 'trek', 'live', 'prosper'],
    '👌': ['ok', 'perfect', 'good', 'fine', 'okay', 'gut', 'perfekt'],
    '🤌': ['italian', 'pinched', 'fingers', 'italienisch', 'cosa'],
    '🤏': ['pinching', 'small', 'tiny', 'little', 'klein', 'wenig'],
    '✌️': ['peace', 'victory', 'frieden', 'sieg', 'zwei'],
    '🤞': ['crossed', 'fingers', 'luck', 'hope', 'glück', 'daumen', 'drücken'],
    '🤟': ['love', 'you', 'sign', 'liebe', 'ily'],
    '🤘': ['rock', 'metal', 'horns', 'devil', 'musik', 'heavy'],
    '🤙': ['call', 'me', 'shaka', 'hang', 'loose', 'anrufen'],
    '👈': ['pointing', 'left', 'links', 'zeigen', 'finger'],
    '👉': ['pointing', 'right', 'rechts', 'zeigen', 'finger'],
    '👆': ['pointing', 'up', 'hoch', 'oben', 'zeigen', 'finger'],
    '🖕': ['middle', 'finger', 'rude', 'offensive', 'mittelfinger', 'fuck'],
    '👇': ['pointing', 'down', 'unten', 'runter', 'zeigen', 'finger'],
    '☝️': ['index', 'pointing', 'up', 'one', 'first', 'zeigen'],
    '👍': ['thumbs', 'up', 'good', 'like', 'yes', 'gut', 'daumen', 'ja'],
    '👎': ['thumbs', 'down', 'bad', 'dislike', 'no', 'schlecht', 'daumen', 'nein'],
    '✊': ['fist', 'punch', 'power', 'strength', 'faust', 'kraft'],
    '👊': ['fist', 'punch', 'bump', 'power', 'faust', 'schlag'],
    '🤛': ['left', 'fist', 'bump', 'punch', 'faust', 'links'],
    '🤜': ['right', 'fist', 'bump', 'punch', 'faust', 'rechts'],
    '👏': ['clapping', 'applause', 'well', 'done', 'klatschen', 'applaus'],
    '🙌': ['raising', 'hands', 'praise', 'celebration', 'hurray', 'juhu'],
    '👐': ['open', 'hands', 'hug', 'embrace', 'offene', 'hände'],
    '🤲': ['palms', 'up', 'prayer', 'cupped', 'hands', 'beten'],
    '🤝': ['handshake', 'deal', 'agreement', 'händedruck', 'einigung'],
    '🙏': ['prayer', 'please', 'thank', 'you', 'beten', 'danke', 'bitte'],
    '✍️': ['writing', 'hand', 'author', 'schreiben', 'autor'],
    '💅': ['nail', 'polish', 'care', 'beauty', 'nagel', 'lackieren'],
    '🤳': ['selfie', 'camera', 'phone', 'photo', 'selbstporträt'],
    '💪': ['muscle', 'strong', 'gym', 'workout', 'muskel', 'stark'],
    '🦾': ['mechanical', 'arm', 'prosthetic', 'robot', 'roboter'],
    '🦿': ['mechanical', 'leg', 'prosthetic', 'robot', 'bein'],
    '🦵': ['leg', 'kick', 'limb', 'bein', 'treten'],
    '🦶': ['foot', 'kick', 'stomp', 'fuß', 'treten'],
    '👂': ['ear', 'hearing', 'listen', 'ohr', 'hören', 'zuhören'],
    '🦻': ['ear', 'hearing', 'aid', 'hörgerät', 'schwerhörig'],
    '👃': ['nose', 'smell', 'scent', 'nase', 'riechen'],
    '🧠': ['brain', 'smart', 'think', 'intelligence', 'gehirn', 'denken'],
    '🦷': ['tooth', 'dental', 'dentist', 'zahn', 'zahnarzt'],
    '🦴': ['bone', 'skeleton', 'dog', 'knochen', 'skelett'],
    '👀': ['eyes', 'looking', 'watching', 'see', 'augen', 'schauen'],
    '👁️': ['eye', 'see', 'watch', 'look', 'auge', 'sehen'],
    '👅': ['tongue', 'taste', 'lick', 'zunge', 'lecken', 'schmecken'],
    '👄': ['mouth', 'lips', 'kiss', 'mund', 'lippen', 'kuss'],

    // ===== HERZEN & LIEBE =====
    '❤️': ['red', 'heart', 'love', 'romance', 'rotes', 'herz', 'liebe'],
    '🧡': ['orange', 'heart', 'love', 'oranges', 'herz', 'liebe'],
    '💛': ['yellow', 'heart', 'love', 'gelbes', 'herz', 'liebe'],
    '💚': ['green', 'heart', 'love', 'grünes', 'herz', 'liebe'],
    '💙': ['blue', 'heart', 'love', 'blaues', 'herz', 'liebe'],
    '💜': ['purple', 'heart', 'love', 'lila', 'herz', 'liebe'],
    '🖤': ['black', 'heart', 'love', 'schwarzes', 'herz', 'liebe'],
    '🤍': ['white', 'heart', 'love', 'weißes', 'herz', 'liebe'],
    '🤎': ['brown', 'heart', 'love', 'braunes', 'herz', 'liebe'],
    '💔': ['broken', 'heart', 'sad', 'breakup', 'gebrochenes', 'herz', 'trennung'],
    '❣️': ['heart', 'exclamation', 'love', 'herz', 'ausrufezeichen'],
    '💕': ['two', 'hearts', 'love', 'couple', 'zwei', 'herzen'],
    '💞': ['revolving', 'hearts', 'love', 'herzen', 'liebe'],
    '💓': ['beating', 'heart', 'love', 'schlagendes', 'herz'],
    '💗': ['growing', 'heart', 'love', 'wachsendes', 'herz'],
    '💖': ['sparkling', 'heart', 'love', 'glitzerndes', 'herz'],
    '💘': ['heart', 'arrow', 'cupid', 'love', 'herz', 'pfeil', 'amor'],
    '💝': ['heart', 'ribbon', 'gift', 'present', 'geschenk', 'herz'],
    '💟': ['heart', 'decoration', 'love', 'herz', 'dekoration'],
    '💌': ['love', 'letter', 'heart', 'mail', 'liebesbrief', 'post'],
    '💋': ['kiss', 'lips', 'love', 'kuss', 'lippen'],
    '💐': ['bouquet', 'flowers', 'gift', 'blumenstrauß', 'blumen'],
    '🌹': ['rose', 'flower', 'romance', 'love', 'red', 'rot', 'blume'],
    '🥀': ['wilted', 'flower', 'sad', 'dead', 'verwelkte', 'blume'],
    '🌺': ['hibiscus', 'flower', 'tropical', 'blume', 'tropisch'],
    '🌸': ['cherry', 'blossom', 'flower', 'spring', 'kirschblüte', 'frühling'],
    '🌼': ['daisy', 'flower', 'yellow', 'gänseblümchen', 'gelb'],
    '🌻': ['sunflower', 'flower', 'yellow', 'sun', 'sonnenblume'],
    '🌷': ['tulip', 'flower', 'spring', 'tulpe', 'frühling'],

    // ===== TIERE =====
    '🐶': ['dog', 'puppy', 'pet', 'cute', 'hund', 'welpe', 'haustier'],
    '🐱': ['cat', 'kitten', 'pet', 'cute', 'katze', 'kätzchen', 'haustier'],
    '🐭': ['mouse', 'small', 'cute', 'maus', 'klein', 'niedlich'],
    '🐹': ['hamster', 'pet', 'small', 'cute', 'haustier', 'klein'],
    '🐰': ['rabbit', 'bunny', 'cute', 'easter', 'hase', 'kaninchen', 'ostern'],
    '🦊': ['fox', 'clever', 'orange', 'fuchs', 'schlau', 'orange'],
    '🐻': ['bear', 'cute', 'brown', 'bär', 'niedlich', 'braun'],
    '🐼': ['panda', 'cute', 'china', 'black', 'white', 'niedlich', 'schwarz', 'weiß'],
    '🐻‍❄️': ['polar', 'bear', 'white', 'cold', 'eisbär', 'weiß', 'kalt'],
    '🐨': ['koala', 'cute', 'australia', 'niedlich', 'australien'],
    '🐯': ['tiger', 'strong', 'orange', 'stripes', 'stark', 'streifen'],
    '🦁': ['lion', 'king', 'strong', 'löwe', 'könig', 'stark'],
    '🐮': ['cow', 'milk', 'farm', 'kuh', 'milch', 'bauernhof'],
    '🐷': ['pig', 'pink', 'farm', 'schwein', 'rosa', 'bauernhof'],
    '🐽': ['pig', 'nose', 'snout', 'schwein', 'nase', 'schnauze'],
    '🐸': ['frog', 'green', 'pond', 'frosch', 'grün', 'teich'],
    '🐵': ['monkey', 'face', 'banana', 'affe', 'gesicht', 'banane'],
    '🙈': ['see', 'no', 'evil', 'monkey', 'nichts', 'sehen', 'affe'],
    '🙉': ['hear', 'no', 'evil', 'monkey', 'nichts', 'hören', 'affe'],
    '🙊': ['speak', 'no', 'evil', 'monkey', 'nichts', 'sagen', 'affe'],
    '🐒': ['monkey', 'banana', 'jungle', 'affe', 'banane', 'dschungel'],
    '🐔': ['chicken', 'farm', 'egg', 'huhn', 'bauernhof', 'ei'],
    '🐧': ['penguin', 'cold', 'ice', 'pinguin', 'kalt', 'eis'],
    '🐦': ['bird', 'fly', 'tweet', 'vogel', 'fliegen', 'zwitschern'],
    '🐤': ['baby', 'chick', 'yellow', 'cute', 'küken', 'gelb', 'niedlich'],
    '🐣': ['hatching', 'chick', 'egg', 'birth', 'küken', 'schlüpfen', 'ei'],
    '🐥': ['front', 'facing', 'baby', 'chick', 'küken', 'gelb'],
    '🦆': ['duck', 'water', 'pond', 'ente', 'wasser', 'teich'],
    '🦅': ['eagle', 'strong', 'america', 'adler', 'stark', 'amerika'],
    '🦉': ['owl', 'wise', 'night', 'eule', 'weise', 'nacht'],
    '🦇': ['bat', 'night', 'halloween', 'fledermaus', 'nacht'],
    '🐺': ['wolf', 'howl', 'moon', 'pack', 'heulen', 'mond', 'rudel'],
    '🐗': ['boar', 'wild', 'pig', 'wildschwein', 'wild', 'schwein'],
    '🐴': ['horse', 'ride', 'gallop', 'pferd', 'reiten', 'galopp'],
    '🦄': ['unicorn', 'magic', 'fantasy', 'rainbow', 'einhorn', 'magie', 'regenbogen'],
    '🐝': ['bee', 'honey', 'buzz', 'flower', 'biene', 'honig', 'summen'],
    '🐛': ['bug', 'insect', 'caterpillar', 'käfer', 'insekt', 'raupe'],
    '🦋': ['butterfly', 'beautiful', 'fly', 'schmetterling', 'schön', 'fliegen'],
    '🐌': ['snail', 'slow', 'shell', 'schnecke', 'langsam', 'schneckenhaus'],
    '🐞': ['ladybug', 'lucky', 'red', 'marienkäfer', 'glück', 'rot'],
    '🐜': ['ant', 'work', 'colony', 'ameise', 'arbeit', 'kolonie'],
    '🦟': ['mosquito', 'bite', 'buzz', 'mücke', 'stechen', 'summen'],
    '🦗': ['cricket', 'chirp', 'night', 'grille', 'zirpen', 'nacht'],
    '🕷️': ['spider', 'web', 'eight', 'legs', 'spinne', 'netz', 'beine'],
    '🕸️': ['spider', 'web', 'trap', 'spinnennetz', 'falle'],
    '🦂': ['scorpion', 'sting', 'desert', 'skorpion', 'stechen', 'wüste'],
    '🐢': ['turtle', 'slow', 'shell', 'schildkröte', 'langsam', 'panzer'],
    '🐍': ['snake', 'long', 'slither', 'schlange', 'lang', 'schlängeln'],
    '🦎': ['lizard', 'reptile', 'gecko', 'echse', 'reptil'],
    '🦖': ['t-rex', 'dinosaur', 'extinct', 'big', 'dinosaurier', 'ausgestorben'],
    '🦕': ['sauropod', 'dinosaur', 'long', 'neck', 'dinosaurier', 'langer', 'hals'],
    '🐙': ['octopus', 'tentacles', 'sea', 'krake', 'tentakel', 'meer'],
    '🦑': ['squid', 'tentacles', 'sea', 'tintenfisch', 'tentakel', 'meer'],
    '🦐': ['shrimp', 'small', 'sea', 'garnele', 'klein', 'meer'],
    '🦞': ['lobster', 'claws', 'red', 'hummer', 'scheren', 'rot'],
    '🦀': ['crab', 'claws', 'beach', 'krabbe', 'scheren', 'strand'],
    '🐡': ['blowfish', 'puffer', 'spikes', 'kugelfisch', 'stacheln'],
    '🐠': ['tropical', 'fish', 'colorful', 'tropischer', 'fisch', 'bunt'],
    '🐟': ['fish', 'swim', 'water', 'fisch', 'schwimmen', 'wasser'],
    '🐬': ['dolphin', 'smart', 'jump', 'delfin', 'intelligent', 'springen'],
    '🐳': ['spouting', 'whale', 'big', 'ocean', 'wal', 'groß', 'ozean'],
    '🐋': ['whale', 'big', 'ocean', 'mammal', 'wal', 'groß', 'ozean'],
    '🦈': ['shark', 'dangerous', 'teeth', 'hai', 'gefährlich', 'zähne'],
    '🐊': ['crocodile', 'dangerous', 'teeth', 'krokodil', 'gefährlich', 'zähne'],
    '🐅': ['tiger', 'stripes', 'jungle', 'tiger', 'streifen', 'dschungel'],
    '🐆': ['leopard', 'spots', 'fast', 'leopard', 'flecken', 'schnell'],
    '🦓': ['zebra', 'stripes', 'africa', 'zebra', 'streifen', 'afrika'],
    '🦍': ['gorilla', 'strong', 'jungle', 'gorilla', 'stark', 'dschungel'],
    '🦧': ['orangutan', 'ape', 'red', 'orangutan', 'affe', 'rot'],
    '🐘': ['elephant', 'big', 'trunk', 'elefant', 'groß', 'rüssel'],
    '🦛': ['hippopotamus', 'big', 'water', 'nilpferd', 'groß', 'wasser'],
    '🦏': ['rhinoceros', 'horn', 'big', 'nashorn', 'horn', 'groß'],
    '🐪': ['camel', 'desert', 'hump', 'kamel', 'wüste', 'höcker'],
    '🐫': ['two', 'hump', 'camel', 'zwei', 'höcker', 'kamel'],
    '🦒': ['giraffe', 'tall', 'neck', 'giraffe', 'groß', 'hals'],
    '🦘': ['kangaroo', 'jump', 'australia', 'känguru', 'springen', 'australien'],
    '🦬': ['bison', 'buffalo', 'strong', 'bison', 'büffel', 'stark'],
    '🐃': ['water', 'buffalo', 'horn', 'wasserbüffel', 'horn'],
    '🐂': ['ox', 'bull', 'strong', 'ochse', 'stier', 'stark'],
    '🐄': ['cow', 'milk', 'moo', 'kuh', 'milch', 'muh'],
    '🐎': ['horse', 'racing', 'fast', 'pferd', 'rennen', 'schnell'],
    '🐖': ['pig', 'farm', 'pink', 'schwein', 'bauernhof', 'rosa'],
    '🐏': ['ram', 'sheep', 'horn', 'widder', 'schaf', 'horn'],
    '🐑': ['ewe', 'sheep', 'wool', 'schaf', 'wolle'],
    '🦙': ['llama', 'alpaca', 'fluffy', 'lama', 'alpaka', 'flauschig'],
    '🐐': ['goat', 'horn', 'beard', 'ziege', 'horn', 'bart'],
    '🦌': ['deer', 'antlers', 'forest', 'reh', 'hirsch', 'geweih', 'wald'],

    // ===== ESSEN & TRINKEN =====
    '🍏': ['green', 'apple', 'fruit', 'healthy', 'grüner', 'apfel', 'obst', 'gesund'],
    '🍎': ['red', 'apple', 'fruit', 'healthy', 'roter', 'apfel', 'obst', 'gesund'],
    '🍐': ['pear', 'fruit', 'green', 'birne', 'obst', 'grün'],
    '🍊': ['orange', 'fruit', 'citrus', 'vitamin', 'orange', 'obst', 'zitrus'],
    '🍋': ['lemon', 'yellow', 'sour', 'citrus', 'zitrone', 'gelb', 'sauer'],
    '🍌': ['banana', 'yellow', 'fruit', 'monkey', 'banane', 'gelb', 'obst'],
    '🍉': ['watermelon', 'summer', 'red', 'green', 'wassermelone', 'sommer', 'rot'],
    '🍇': ['grapes', 'wine', 'purple', 'fruit', 'trauben', 'wein', 'lila'],
    '🍓': ['strawberry', 'red', 'sweet', 'berry', 'erdbeere', 'rot', 'süß'],
    '🫐': ['blueberry', 'blue', 'small', 'berry', 'blaubeere', 'blau', 'klein'],
    '🍈': ['melon', 'cantaloupe', 'orange', 'sweet', 'melone', 'orange', 'süß'],
    '🍒': ['cherries', 'red', 'sweet', 'two', 'kirschen', 'rot', 'süß'],
    '🍑': ['peach', 'orange', 'soft', 'fuzzy', 'pfirsich', 'orange', 'weich'],
    '🥭': ['mango', 'tropical', 'orange', 'sweet', 'mango', 'tropisch', 'süß'],
    '🍍': ['pineapple', 'tropical', 'yellow', 'spiky', 'ananas', 'tropisch', 'gelb'],
    '🥥': ['coconut', 'tropical', 'white', 'milk', 'kokosnuss', 'tropisch', 'weiß'],
    '🥝': ['kiwi', 'green', 'fruit', 'fuzzy', 'kiwi', 'grün', 'obst'],
    '🍅': ['tomato', 'red', 'vegetable', 'salad', 'tomate', 'rot', 'gemüse'],
    '🍆': ['eggplant', 'purple', 'vegetable', 'aubergine', 'lila', 'gemüse'],
    '🥑': ['avocado', 'green', 'healthy', 'toast', 'avocado', 'grün', 'gesund'],
    '🥦': ['broccoli', 'green', 'healthy', 'vegetable', 'brokkoli', 'grün', 'gesund'],
    '🥬': ['leafy', 'greens', 'salad', 'healthy', 'blätter', 'salat', 'gesund'],
    '🥒': ['cucumber', 'green', 'fresh', 'salad', 'gurke', 'grün', 'frisch'],
    '🌶️': ['hot', 'pepper', 'spicy', 'red', 'chili', 'scharf', 'rot'],
    '🫑': ['bell', 'pepper', 'colorful', 'vegetable', 'paprika', 'bunt', 'gemüse'],
    '🌽': ['corn', 'yellow', 'cob', 'vegetable', 'mais', 'gelb', 'kolben'],
    '🥕': ['carrot', 'orange', 'rabbit', 'healthy', 'karotte', 'möhre', 'orange'],
    '🫒': ['olive', 'green', 'oil', 'mediterranean', 'olive', 'grün', 'öl'],
    '🧄': ['garlic', 'white', 'cooking', 'smell', 'knoblauch', 'weiß', 'kochen'],
    '🧅': ['onion', 'cry', 'layers', 'cooking', 'zwiebel', 'weinen', 'kochen'],
    '🥔': ['potato', 'brown', 'vegetable', 'fries', 'kartoffel', 'braun', 'pommes'],
    '🍠': ['sweet', 'potato', 'orange', 'healthy', 'süßkartoffel', 'orange', 'gesund'],
    '🥐': ['croissant', 'french', 'bread', 'buttery', 'croissant', 'französisch', 'brot'],
    '🥯': ['bagel', 'bread', 'round', 'hole', 'bagel', 'brot', 'rund'],
    '🍞': ['bread', 'slice', 'wheat', 'breakfast', 'brot', 'scheibe', 'frühstück'],
    '🥖': ['baguette', 'french', 'bread', 'long', 'baguette', 'französisch', 'lang'],
    '🥨': ['pretzel', 'german', 'salt', 'twisted', 'brezel', 'deutsch', 'salz'],
    '🧀': ['cheese', 'yellow', 'holes', 'mouse', 'käse', 'gelb', 'löcher'],
    '🥚': ['egg', 'white', 'breakfast', 'protein', 'ei', 'weiß', 'frühstück'],
    '🍳': ['cooking', 'egg', 'pan', 'fried', 'kochen', 'ei', 'pfanne'],
    '🧈': ['butter', 'yellow', 'spread', 'dairy', 'butter', 'gelb', 'streich'],
    '🥞': ['pancakes', 'breakfast', 'syrup', 'stack', 'pfannkuchen', 'frühstück'],
    '🧇': ['waffle', 'breakfast', 'syrup', 'squares', 'waffel', 'frühstück'],
    '🥓': ['bacon', 'meat', 'breakfast', 'crispy', 'speck', 'fleisch', 'frühstück'],
    '🥩': ['cut', 'meat', 'steak', 'red', 'fleisch', 'steak', 'rot'],
    '🍗': ['poultry', 'leg', 'chicken', 'drumstick', 'hähnchen', 'schenkel'],
    '🍖': ['meat', 'bone', 'caveman', 'bbq', 'fleisch', 'knochen', 'grill'],
    '🌭': ['hot', 'dog', 'sausage', 'mustard', 'hotdog', 'wurst', 'senf'],
    '🍔': ['hamburger', 'burger', 'meat', 'bun', 'hamburger', 'fleisch', 'brötchen'],
    '🍟': ['french', 'fries', 'potato', 'salt', 'pommes', 'kartoffel', 'salz'],
    '🍕': ['pizza', 'cheese', 'italian', 'slice', 'pizza', 'käse', 'italienisch'],
    '🫓': ['flatbread', 'naan', 'pita', 'bread', 'fladenbrot', 'brot'],
    '🥪': ['sandwich', 'bread', 'filling', 'lunch', 'sandwich', 'brot', 'füllung'],
    '🥙': ['stuffed', 'flatbread', 'falafel', 'wrap', 'gefüllt', 'fladenbrot'],
    '🧆': ['falafel', 'middle', 'eastern', 'fried', 'falafel', 'orientalisch'],
    '🌮': ['taco', 'mexican', 'shell', 'meat', 'taco', 'mexikanisch', 'schale'],
    '🌯': ['burrito', 'wrap', 'mexican', 'beans', 'burrito', 'mexikanisch'],
    '🫔': ['tamale', 'mexican', 'corn', 'husk', 'tamale', 'mexikanisch', 'mais'],
    '🥗': ['green', 'salad', 'healthy', 'vegetables', 'grüner', 'salat', 'gesund'],
    '🥘': ['shallow', 'pan', 'food', 'paella', 'pfanne', 'essen', 'paella'],
    '🫕': ['fondue', 'cheese', 'pot', 'swiss', 'fondue', 'käse', 'topf'],
    '🥫': ['canned', 'food', 'tin', 'preserved', 'dose', 'essen', 'konserve'],
    '🍝': ['spaghetti', 'pasta', 'italian', 'noodles', 'spaghetti', 'nudeln', 'italienisch'],
    '🍜': ['steaming', 'bowl', 'noodles', 'ramen', 'schüssel', 'nudeln', 'suppe'],
    '🍲': ['pot', 'food', 'stew', 'cooking', 'topf', 'essen', 'eintopf'],
    '🍛': ['curry', 'rice', 'indian', 'spicy', 'curry', 'reis', 'scharf'],
    '🍣': ['sushi', 'japanese', 'fish', 'raw', 'sushi', 'japanisch', 'fisch'],
    '🍱': ['bento', 'box', 'japanese', 'lunch', 'bento', 'japanisch', 'lunch'],
    '🥟': ['dumpling', 'filled', 'dough', 'asian', 'teigtasche', 'gefüllt', 'asiatisch'],
    '🦪': ['oyster', 'shell', 'sea', 'pearl', 'auster', 'schale', 'meer'],
    '🍤': ['fried', 'shrimp', 'tempura', 'crispy', 'garnele', 'frittiert', 'knusprig'],
    '🍙': ['rice', 'ball', 'japanese', 'seaweed', 'reis', 'ball', 'japanisch'],
    '🍚': ['cooked', 'rice', 'bowl', 'white', 'gekochter', 'reis', 'schüssel'],
    '🍘': ['rice', 'cracker', 'japanese', 'snack', 'reis', 'cracker', 'japanisch'],
    '🍥': ['fish', 'cake', 'swirl', 'japanese', 'fisch', 'kuchen', 'japanisch'],
    '🥠': ['fortune', 'cookie', 'prediction', 'chinese', 'glückskeks', 'vorhersage'],
    '🥮': ['moon', 'cake', 'chinese', 'festival', 'mondkuchen', 'chinesisch'],
    '🍢': ['oden', 'skewer', 'japanese', 'hot', 'spieß', 'japanisch', 'heiß'],
    '🍡': ['dango', 'sweet', 'japanese', 'stick', 'süß', 'japanisch', 'stick'],
    '🍧': ['shaved', 'ice', 'cold', 'sweet', 'eis', 'kalt', 'süß'],
    '🍨': ['ice', 'cream', 'cold', 'sweet', 'eis', 'kalt', 'süß'],
    '🍦': ['soft', 'serve', 'ice', 'cream', 'softeis', 'eis'],
    '🥧': ['pie', 'dessert', 'crust', 'filling', 'kuchen', 'nachspeise'],
    '🧁': ['cupcake', 'muffin', 'frosting', 'sweet', 'cupcake', 'muffin', 'süß'],
    '🍰': ['shortcake', 'dessert', 'sweet', 'cake', 'kuchen', 'nachspeise', 'süß'],
    '🎂': ['birthday', 'cake', 'candles', 'celebration', 'geburtstagskuchen', 'kerzen'],
    '🍮': ['custard', 'flan', 'dessert', 'sweet', 'pudding', 'nachspeise', 'süß'],
    '🍭': ['lollipop', 'candy', 'sweet', 'stick', 'lutscher', 'süßigkeit', 'stick'],
    '🍬': ['candy', 'sweet', 'wrapper', 'treat', 'bonbon', 'süßigkeit', 'papier'],
    '🍫': ['chocolate', 'bar', 'sweet', 'cocoa', 'schokolade', 'süß', 'kakao'],
    '🍿': ['popcorn', 'movie', 'corn', 'snack', 'popcorn', 'film', 'mais'],
    '🍩': ['doughnut', 'donut', 'sweet', 'glazed', 'donut', 'süß', 'glasiert'],
    '🍪': ['cookie', 'sweet', 'chocolate', 'chip', 'keks', 'süß', 'schokolade'],

    // ===== AKTIVITÄTEN & SPORT =====
    '⚽': ['soccer', 'football', 'ball', 'sport', 'fußball', 'ball', 'sport'],
    '🏀': ['basketball', 'ball', 'sport', 'hoop', 'basketball', 'ball', 'korb'],
    '🏈': ['american', 'football', 'ball', 'sport', 'amerikanisch', 'football'],
    '⚾': ['baseball', 'ball', 'sport', 'bat', 'baseball', 'ball', 'schläger'],
    '🥎': ['softball', 'ball', 'sport', 'yellow', 'softball', 'ball', 'gelb'],
    '🎾': ['tennis', 'ball', 'sport', 'racket', 'tennis', 'ball', 'schläger'],
    '🏐': ['volleyball', 'ball', 'sport', 'net', 'volleyball', 'ball', 'netz'],
    '🏉': ['rugby', 'football', 'ball', 'sport', 'rugby', 'football', 'ball'],
    '🥏': ['flying', 'disc', 'frisbee', 'sport', 'frisbee', 'scheibe', 'sport'],
    '🎱': ['pool', 'eight', 'ball', 'billiard', 'billard', 'acht', 'ball'],
    '🪀': ['yo-yo', 'toy', 'string', 'up', 'down', 'jo-jo', 'spielzeug'],
    '🏓': ['ping', 'pong', 'table', 'tennis', 'tischtennis', 'ping', 'pong'],
    '🏸': ['badminton', 'racquet', 'sport', 'shuttlecock', 'badminton', 'federball'],
    '🏒': ['ice', 'hockey', 'stick', 'puck', 'eishockey', 'schläger', 'puck'],
    '🏑': ['field', 'hockey', 'stick', 'ball', 'feldhockey', 'schläger'],
    '🥍': ['lacrosse', 'stick', 'ball', 'sport', 'lacrosse', 'schläger'],
    '🏏': ['cricket', 'bat', 'ball', 'wicket', 'cricket', 'schläger', 'ball'],
    '🪃': ['boomerang', 'return', 'throw', 'australian', 'bumerang', 'werfen'],
    '🥅': ['goal', 'net', 'sport', 'soccer', 'tor', 'netz', 'fußball'],
    '⛳': ['flag', 'hole', 'golf', 'course', 'flagge', 'loch', 'golf'],
    '🪁': ['kite', 'fly', 'wind', 'string', 'drachen', 'fliegen', 'wind'],
    '🏹': ['bow', 'arrow', 'archery', 'target', 'bogen', 'pfeil', 'bogenschießen'],
    '🎣': ['fishing', 'pole', 'fish', 'hook', 'angeln', 'angel', 'fisch'],
    '🤿': ['diving', 'mask', 'snorkel', 'underwater', 'tauchen', 'maske', 'schnorchel'],
    '🥊': ['boxing', 'glove', 'fight', 'punch', 'boxen', 'handschuh', 'kampf'],
    '🥋': ['martial', 'arts', 'uniform', 'karate', 'kampfsport', 'anzug'],
    '🎽': ['running', 'shirt', 'marathon', 'vest', 'laufen', 'hemd', 'marathon'],
    '🛹': ['skateboard', 'skate', 'wheels', 'trick', 'skateboard', 'rollen'],
    '🛼': ['roller', 'skate', 'wheels', 'disco', 'rollschuh', 'rollen'],
    '🛷': ['sled', 'snow', 'winter', 'slide', 'schlitten', 'schnee', 'winter'],
    '⛸️': ['ice', 'skate', 'winter', 'rink', 'schlittschuh', 'eis', 'winter'],
    '🥌': ['curling', 'stone', 'ice', 'sport', 'curling', 'stein', 'eis'],
    '🎿': ['skis', 'snow', 'winter', 'mountain', 'ski', 'schnee', 'berg'],
    '⛷️': ['skier', 'skiing', 'snow', 'mountain', 'skifahren', 'schnee', 'berg'],
    '🏂': ['snowboard', 'snow', 'winter', 'mountain', 'snowboard', 'schnee'],
    '🪂': ['parachute', 'skydiving', 'jump', 'fall', 'fallschirm', 'springen'],
    '🏋️': ['weight', 'lifting', 'gym', 'strong', 'gewichtheben', 'fitnessstudio'],
    '🤼': ['wrestling', 'fight', 'grapple', 'sport', 'ringen', 'kampf'],
    '🤸': ['cartwheel', 'gymnastics', 'flip', 'acrobat', 'rad', 'gymnastik'],
    '⛹️': ['person', 'bouncing', 'ball', 'basketball', 'basketball', 'dribbeln'],
    '🤺': ['fencing', 'sword', 'sport', 'mask', 'fechten', 'schwert', 'maske'],
    '🤾': ['handball', 'ball', 'throw', 'sport', 'handball', 'ball', 'werfen'],
    '🏌️': ['golf', 'swing', 'club', 'ball', 'golf', 'schwung', 'schläger'],
    '🏇': ['horse', 'racing', 'jockey', 'gallop', 'pferd', 'rennen', 'jockey'],
    '🧘': ['meditation', 'yoga', 'zen', 'peace', 'meditation', 'yoga', 'ruhe'],
    '🏄': ['surfing', 'wave', 'board', 'ocean', 'surfen', 'welle', 'brett'],
    '🏊': ['swimming', 'pool', 'water', 'stroke', 'schwimmen', 'pool', 'wasser'],
    '🤽': ['water', 'polo', 'ball', 'swimming', 'wasserball', 'schwimmen'],
    '🚣': ['rowing', 'boat', 'oars', 'water', 'rudern', 'boot', 'ruder'],
    '🧗': ['climbing', 'rock', 'mountain', 'rope', 'klettern', 'fels', 'berg'],
    '🚵': ['mountain', 'biking', 'bicycle', 'trail', 'mountainbike', 'fahrrad'],
    '🚴': ['biking', 'bicycle', 'cycling', 'pedal', 'fahrrad', 'radfahren'],
    '🏆': ['trophy', 'winner', 'gold', 'first', 'trophäe', 'gewinner', 'gold'],
    '🥇': ['first', 'place', 'medal', 'gold', 'erster', 'platz', 'medaille'],
    '🥈': ['second', 'place', 'medal', 'silver', 'zweiter', 'platz', 'silber'],
    '🥉': ['third', 'place', 'medal', 'bronze', 'dritter', 'platz', 'bronze'],
    '🏅': ['sports', 'medal', 'award', 'achievement', 'sportmedaille', 'auszeichnung'],
    '🎖️': ['military', 'medal', 'honor', 'award', 'militär', 'medaille', 'ehre'],
    '🏵️': ['rosette', 'award', 'prize', 'decoration', 'rosette', 'preis'],
    '🎗️': ['reminder', 'ribbon', 'cause', 'awareness', 'schleife', 'bewusstsein'],
    '🎫': ['ticket', 'admission', 'event', 'show', 'ticket', 'einlass', 'veranstaltung'],
    '🎟️': ['admission', 'tickets', 'event', 'show', 'eintrittskarte', 'veranstaltung'],
    '🎪': ['circus', 'tent', 'show', 'entertainment', 'zirkus', 'zelt', 'show'],
    '🤹': ['juggling', 'balls', 'skill', 'circus', 'jonglieren', 'bälle'],
    '🎭': ['performing', 'arts', 'theater', 'drama', 'theater', 'drama', 'kunst'],
    '🩰': ['ballet', 'shoes', 'dance', 'graceful', 'ballett', 'schuhe', 'tanzen'],
    '🎨': ['artist', 'palette', 'paint', 'creative', 'künstler', 'palette', 'malen'],
    '🎬': ['clapper', 'board', 'movie', 'film', 'filmklappe', 'film'],
    '🎤': ['microphone', 'singing', 'karaoke', 'performance', 'mikrofon', 'singen'],
    '🎧': ['headphones', 'music', 'listening', 'audio', 'kopfhörer', 'musik'],
    '🎼': ['musical', 'score', 'notes', 'composition', 'noten', 'komposition'],
    '🎹': ['musical', 'keyboard', 'piano', 'keys', 'klavier', 'tasten'],
    '🥁': ['drum', 'percussion', 'beat', 'rhythm', 'trommel', 'schlagzeug'],
    '🪘': ['long', 'drum', 'percussion', 'beat', 'trommel', 'schlagzeug'],
    '🎷': ['saxophone', 'jazz', 'music', 'brass', 'saxophon', 'jazz', 'musik'],
    '🎺': ['trumpet', 'brass', 'music', 'horn', 'trompete', 'blasinstrument'],
    '🪗': ['accordion', 'music', 'folk', 'squeeze', 'akkordeon', 'musik'],
    '🎸': ['guitar', 'music', 'strings', 'rock', 'gitarre', 'musik', 'saiten'],
    '🪕': ['banjo', 'music', 'strings', 'folk', 'banjo', 'musik', 'saiten'],
    '🎻': ['violin', 'music', 'strings', 'classical', 'geige', 'musik', 'klassisch'],
    '🎲': ['dice', 'game', 'random', 'gambling', 'würfel', 'spiel', 'zufall'],
    '♟️': ['chess', 'pawn', 'strategy', 'game', 'schach', 'bauer', 'strategie'],
    '🎯': ['direct', 'hit', 'target', 'bullseye', 'zielscheibe', 'treffer'],
    '🎳': ['bowling', 'pins', 'strike', 'alley', 'bowling', 'kegel', 'strike'],
    '🎮': ['video', 'game', 'controller', 'gaming', 'videospiel', 'controller'],
    '🎰': ['slot', 'machine', 'gambling', 'casino', 'spielautomat', 'glücksspiel'],
    '🧩': ['puzzle', 'piece', 'jigsaw', 'solve', 'puzzle', 'teil', 'lösen'],

    // ===== OBJEKTE & TECHNOLOGIE =====
    '⌚': ['watch', 'time', 'wrist', 'smart', 'uhr', 'zeit', 'handgelenk'],
    '📱': ['mobile', 'phone', 'smartphone', 'call', 'handy', 'smartphone', 'anruf'],
    '📲': ['mobile', 'phone', 'arrow', 'call', 'handy', 'pfeil', 'anruf'],
    '💻': ['laptop', 'computer', 'work', 'technology', 'laptop', 'computer', 'arbeit'],
    '⌨️': ['keyboard', 'typing', 'computer', 'keys', 'tastatur', 'tippen', 'tasten'],
    '🖥️': ['desktop', 'computer', 'monitor', 'screen', 'desktop', 'bildschirm'],
    '🖨️': ['printer', 'paper', 'ink', 'document', 'drucker', 'papier', 'dokument'],
    '🖱️': ['computer', 'mouse', 'click', 'cursor', 'computermaus', 'klicken'],
    '🖲️': ['trackball', 'mouse', 'computer', 'cursor', 'trackball', 'maus'],
    '🕹️': ['joystick', 'game', 'controller', 'arcade', 'joystick', 'spiel'],
    '🗜️': ['clamp', 'tool', 'compress', 'squeeze', 'schraubstock', 'werkzeug'],
    '💽': ['minidisc', 'data', 'storage', 'disc', 'minidisc', 'daten'],
    '💾': ['floppy', 'disk', 'save', 'storage', 'diskette', 'speichern'],
    '💿': ['optical', 'disc', 'cd', 'music', 'cd', 'musik', 'scheibe'],
    '📀': ['dvd', 'disc', 'movie', 'data', 'dvd', 'film', 'daten'],
    '📼': ['videocassette', 'tape', 'movie', 'old', 'videokassette', 'band'],
    '📷': ['camera', 'photo', 'picture', 'snapshot', 'kamera', 'foto', 'bild'],
    '📸': ['camera', 'flash', 'photo', 'picture', 'kamera', 'blitz', 'foto'],
    '📹': ['video', 'camera', 'recording', 'movie', 'videokamera', 'aufnahme'],
    '🎥': ['movie', 'camera', 'film', 'cinema', 'filmkamera', 'kino'],
    '📽️': ['film', 'projector', 'movie', 'cinema', 'filmprojektor', 'kino'],
    '🎞️': ['film', 'frames', 'movie', 'reel', 'filmstreifen', 'rolle'],
    '📞': ['telephone', 'receiver', 'call', 'phone', 'telefon', 'hörer', 'anruf'],
    '☎️': ['telephone', 'phone', 'call', 'old', 'telefon', 'anruf', 'alt'],
    '📟': ['pager', 'beeper', 'message', 'communication', 'pager', 'nachricht'],
    '📠': ['fax', 'machine', 'document', 'send', 'fax', 'maschine', 'dokument'],
    '📺': ['television', 'tv', 'watch', 'screen', 'fernseher', 'tv', 'bildschirm'],
    '📻': ['radio', 'music', 'listen', 'broadcast', 'radio', 'musik', 'hören'],
    '🎙️': ['studio', 'microphone', 'recording', 'podcast', 'studiomikrofon', 'aufnahme'],
    '🎚️': ['level', 'slider', 'audio', 'control', 'schieberegler', 'audio'],
    '🎛️': ['control', 'knobs', 'audio', 'mixer', 'bedienfeld', 'mischpult'],
    '🧭': ['compass', 'direction', 'navigation', 'north', 'kompass', 'richtung'],
    '⏱️': ['stopwatch', 'timer', 'time', 'race', 'stoppuhr', 'timer', 'zeit'],
    '⏲️': ['timer', 'clock', 'countdown', 'alarm', 'timer', 'countdown', 'wecker'],
    '⏰': ['alarm', 'clock', 'wake', 'up', 'wecker', 'aufwachen', 'zeit'],
    '🕰️': ['mantelpiece', 'clock', 'time', 'old', 'standuhrkaminfeuler', 'zeit'],
    '⌛': ['hourglass', 'time', 'sand', 'waiting', 'sanduhr', 'zeit', 'warten'],
    '⏳': ['hourglass', 'flowing', 'sand', 'time', 'sanduhr', 'fließend', 'zeit'],
    '📡': ['satellite', 'antenna', 'communication', 'space', 'satellit', 'kommunikation'],
    '🔋': ['battery', 'power', 'energy', 'charge', 'batterie', 'strom', 'energie'],
    '🔌': ['electric', 'plug', 'power', 'outlet', 'stecker', 'strom', 'steckdose'],
    '💡': ['light', 'bulb', 'idea', 'bright', 'glühbirne', 'idee', 'hell'],
    '🔦': ['flashlight', 'torch', 'light', 'dark', 'taschenlampe', 'licht'],
    '🕯️': ['candle', 'flame', 'light', 'romantic', 'kerze', 'flamme', 'romantisch'],
    '🪔': ['diya', 'lamp', 'oil', 'light', 'öllampe', 'licht'],
    '🧯': ['fire', 'extinguisher', 'safety', 'emergency', 'feuerlöscher', 'sicherheit'],
    '🛢️': ['oil', 'drum', 'barrel', 'fuel', 'ölfass', 'treibstoff'],
    '💸': ['money', 'with', 'wings', 'flying', 'geld', 'flügel', 'ausgeben'],
    '💵': ['dollar', 'banknote', 'money', 'usa', 'dollar', 'geldschein'],
    '💴': ['yen', 'banknote', 'money', 'japan', 'yen', 'geldschein', 'japan'],
    '💶': ['euro', 'banknote', 'money', 'europe', 'euro', 'geldschein', 'europa'],
    '💷': ['pound', 'banknote', 'money', 'uk', 'pfund', 'geldschein'],
    '🪙': ['coin', 'money', 'currency', 'round', 'münze', 'geld', 'währung'],
    '💰': ['money', 'bag', 'dollar', 'rich', 'geldsack', 'reich'],
    '💳': ['credit', 'card', 'payment', 'bank', 'kreditkarte', 'zahlung', 'bank'],
    '💎': ['gem', 'stone', 'diamond', 'precious', 'edelstein', 'diamant'],
    '⚖️': ['balance', 'scale', 'justice', 'law', 'waage', 'gerechtigkeit', 'gesetz'],
    '🪜': ['ladder', 'climb', 'up', 'steps', 'leiter', 'klettern', 'stufen'],
    '🧰': ['toolbox', 'tools', 'repair', 'fix', 'werkzeugkasten', 'reparieren'],
    '🪛': ['screwdriver', 'tool', 'repair', 'screw', 'schraubenzieher', 'werkzeug'],
    '🔧': ['wrench', 'tool', 'repair', 'fix', 'schraubenschlüssel', 'reparieren'],
    '🔨': ['hammer', 'tool', 'nail', 'build', 'hammer', 'nagel', 'bauen'],
    '⚒️': ['hammer', 'pick', 'tools', 'mining', 'hammer', 'spitzhacke', 'werkzeug'],
    '🛠️': ['hammer', 'wrench', 'tools', 'repair', 'werkzeug', 'reparieren'],
    '⛏️': ['pick', 'mining', 'dig', 'tool', 'spitzhacke', 'graben', 'werkzeug'],
    '🔩': ['nut', 'bolt', 'screw', 'fastener', 'schraube', 'mutter'],
    '⚙️': ['gear', 'cog', 'settings', 'mechanical', 'zahnrad', 'einstellungen'],
    '🪤': ['mouse', 'trap', 'catch', 'spring', 'mausefalle', 'fangen'],
    '🧱': ['brick', 'wall', 'build', 'construction', 'ziegel', 'wand', 'bauen'],
    '⛓️': ['chains', 'link', 'metal', 'connect', 'kette', 'verbindung', 'metall'],
    '🧲': ['magnet', 'attract', 'magnetic', 'pull', 'magnet', 'anziehen'],
    '🔫': ['pistol', 'gun', 'weapon', 'shoot', 'pistole', 'waffe', 'schießen'],
    '💣': ['bomb', 'explosive', 'danger', 'boom', 'bombe', 'explosiv', 'gefahr'],
    '🧨': ['firecracker', 'dynamite', 'explosive', 'bang', 'feuerwerkskörper'],
    '🪓': ['axe', 'wood', 'chop', 'tool', 'axt', 'holz', 'hacken'],
    '🔪': ['kitchen', 'knife', 'cut', 'sharp', 'küchenmesser', 'schneiden'],
    '🗡️': ['dagger', 'knife', 'weapon', 'sharp', 'dolch', 'messer', 'waffe'],
    '⚔️': ['crossed', 'swords', 'fight', 'battle', 'gekreuzte', 'schwerter', 'kampf'],
    '🛡️': ['shield', 'protection', 'defend', 'guard', 'schild', 'schutz'],

    // ===== SYMBOLE & ZEICHEN =====
    '⭐': ['star', 'favorite', 'rating', 'excellent', 'stern', 'favorit', 'bewertung'],
    '🌟': ['glowing', 'star', 'shiny', 'bright', 'leuchtender', 'stern', 'hell'],
    '✨': ['sparkles', 'magic', 'shiny', 'clean', 'funken', 'magie', 'glänzend'],
    '⚡': ['lightning', 'bolt', 'fast', 'electric', 'blitz', 'schnell', 'elektrisch'],
    '💫': ['dizzy', 'star', 'sparkle', 'magic', 'schwindelig', 'stern', 'magie'],
    '🌙': ['crescent', 'moon', 'night', 'sleep', 'sichelmond', 'nacht', 'schlafen'],
    '☀️': ['sun', 'sunny', 'bright', 'day', 'sonne', 'sonnig', 'hell', 'tag'],
    '⛅': ['partly', 'cloudy', 'sun', 'cloud', 'teilweise', 'bewölkt', 'sonne'],
    '⛈️': ['thunder', 'cloud', 'rain', 'storm', 'gewitter', 'wolke', 'sturm'],
    '🌤️': ['sun', 'behind', 'small', 'cloud', 'sonne', 'hinter', 'wolke'],
    '🌥️': ['sun', 'behind', 'large', 'cloud', 'sonne', 'große', 'wolke'],
    '🌦️': ['sun', 'behind', 'rain', 'cloud', 'sonne', 'regenwolke'],
    '🌧️': ['cloud', 'with', 'rain', 'weather', 'wolke', 'regen', 'wetter'],
    '🌩️': ['cloud', 'with', 'lightning', 'storm', 'wolke', 'blitz', 'sturm'],
    '🌨️': ['cloud', 'with', 'snow', 'winter', 'wolke', 'schnee', 'winter'],
    '❄️': ['snowflake', 'cold', 'winter', 'ice', 'schneeflocke', 'kalt'],
    '🌬️': ['wind', 'face', 'blow', 'breeze', 'windgesicht', 'blasen', 'brise'],
    '💨': ['dashing', 'away', 'fast', 'smoke', 'weglaufen', 'schnell', 'rauch'],
    '🌪️': ['tornado', 'cyclone', 'storm', 'wind', 'tornado', 'zyklon', 'sturm'],
    '🌈': ['rainbow', 'colors', 'rain', 'sun', 'regenbogen', 'farben'],
    '☂️': ['umbrella', 'rain', 'protection', 'wet', 'regenschirm', 'schutz'],
    '☔': ['umbrella', 'with', 'rain', 'drops', 'regenschirm', 'tropfen'],
    '💧': ['droplet', 'water', 'tear', 'liquid', 'tropfen', 'wasser', 'träne'],
    '💦': ['sweat', 'droplets', 'water', 'splash', 'schweißtropfen', 'spritzer'],
    '🌊': ['water', 'wave', 'ocean', 'sea', 'wasserwelle', 'ozean', 'meer'],
    '🔥': ['fire', 'flame', 'hot', 'burn', 'feuer', 'flamme', 'heiß'],
    '🎆': ['fireworks', 'celebration', 'party', 'boom', 'feuerwerk', 'feier'],
    '🎇': ['sparkler', 'fireworks', 'celebration', 'light', 'wunderkerze'],
    '🌠': ['shooting', 'star', 'wish', 'night', 'sternschnuppe', 'wunsch'],
    '💯': ['hundred', 'points', 'perfect', 'score', 'hundert', 'punkte', 'perfekt'],
    '💢': ['anger', 'symbol', 'mad', 'angry', 'wut', 'symbol', 'sauer'],
    '💬': ['speech', 'balloon', 'talk', 'chat', 'sprechblase', 'reden'],
    '👁️‍🗨️': ['eye', 'speech', 'bubble', 'witness', 'auge', 'sprechblase'],
    '🗨️': ['left', 'speech', 'bubble', 'talk', 'linke', 'sprechblase'],
    '🗯️': ['right', 'anger', 'bubble', 'mad', 'rechte', 'wutblase'],
    '💭': ['thought', 'balloon', 'thinking', 'dream', 'denkblase', 'träumen'],
    '💤': ['zzz', 'sleeping', 'tired', 'sleep', 'zzz', 'schlafen', 'müde'],
    '💮': ['white', 'flower', 'blossom', 'stamp', 'weiße', 'blume'],
    '♠️': ['spade', 'suit', 'cards', 'black', 'pik', 'karten', 'schwarz'],
    '♥️': ['heart', 'suit', 'cards', 'red', 'herz', 'karten', 'rot'],
    '♦️': ['diamond', 'suit', 'cards', 'red', 'karo', 'karten', 'rot'],
    '♣️': ['club', 'suit', 'cards', 'black', 'kreuz', 'karten', 'schwarz'],
    '🃏': ['joker', 'card', 'wild', 'game', 'joker', 'karte', 'spiel'],
    '🎴': ['flower', 'playing', 'cards', 'japanese', 'blumen', 'spielkarten'],
    '🔇': ['muted', 'speaker', 'no', 'sound', 'stumm', 'lautsprecher'],
    '🔈': ['speaker', 'low', 'volume', 'quiet', 'lautsprecher', 'leise'],
    '🔉': ['speaker', 'medium', 'volume', 'sound', 'lautsprecher', 'mittel'],
    '🔊': ['speaker', 'high', 'volume', 'loud', 'lautsprecher', 'laut'],
    '📢': ['loudspeaker', 'announcement', 'megaphone', 'loud', 'megafon'],
    '📣': ['megaphone', 'cheering', 'announcement', 'loud', 'megafon'],
    '📯': ['postal', 'horn', 'trumpet', 'announce', 'posthorn', 'trompete'],
    '🔔': ['bell', 'notification', 'ring', 'sound', 'glocke', 'benachrichtigung'],
    '🔕': ['bell', 'with', 'slash', 'muted', 'glocke', 'durchgestrichen'],
    '🎵': ['musical', 'note', 'music', 'sound', 'musiknote', 'musik'],
    '🎶': ['musical', 'notes', 'music', 'melody', 'musiknoten', 'melodie'],
    '🔀': ['twisted', 'arrows', 'shuffle', 'random', 'verdrehte', 'pfeile'],
    '🔁': ['repeat', 'button', 'loop', 'again', 'wiederholen', 'schleife'],
    '🔂': ['repeat', 'single', 'button', 'one', 'wiederholen', 'einmal'],
    '⏯️': ['play', 'pause', 'button', 'control', 'wiedergabe', 'pause'],
    '⏮️': ['last', 'track', 'button', 'previous', 'letzter', 'titel'],
    '⏭️': ['next', 'track', 'button', 'forward', 'nächster', 'titel'],
    '⏹️': ['stop', 'button', 'halt', 'end', 'stopp', 'button', 'ende'],
    '⏺️': ['record', 'button', 'circle', 'red', 'aufnahme', 'button', 'rot'],
    '⏸️': ['pause', 'button', 'stop', 'wait', 'pause', 'button', 'warten'],
    '⏏️': ['eject', 'button', 'remove', 'out', 'auswerfen', 'button']
};

